require:
  - rubocop-jekyll
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - script/**/*
    - spec/fixtures/**/*
    - spec/scenarios/**/*
    - spec/spec_helper.rb
    - templates/**/*
    - vendor/**/*
    - Gemfile
    - Rakefile
    - coffeebrew_jekyll_archives.gemspec
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false
