archives:
  invalid: "key"
  navigation:
    invalid: "navigation_key"
  title_format:
    invalid: "nested_key"
    root:
      invalid: "nested_key"
    year:
      invalid: "nested_key"
    month:
      invalid: "nested_key"
    day:
      invalid: "nested_key"
  permalink:
    invalid: "key"
