archives:
  title_format:
    root:
      type: "string"
      style: "/articles"
    year:
      type: "string"
      style: "Year %{year}"
    month:
      type: "date"
      style: "%B, %Y"
    day:
      type: "date"
      style: "%Y-%b-%d"
